"use client";

import { useTheme } from "next-themes";
import { toast } from "sonner";

import { Avatar } from "@/components/ui/Avatar";
import { Button } from "@/components/ui/Button";
import { Field, Input, Select } from "@/components/ui/Field";
import { useMe } from "@/lib/queries";

function Card({ title, description, children, soon }: { title: string; description: string; children: React.ReactNode; soon?: boolean }) {
  return (
    <section className="rounded-xl border border-border bg-surface p-5 shadow-card">
      <div className="mb-4 flex items-start justify-between gap-3">
        <div>
          <h2 className="text-[15px] font-semibold">{title}</h2>
          <p className="text-[13px] text-muted">{description}</p>
        </div>
        {soon && <span className="rounded-full bg-brand-soft px-2 py-0.5 text-[11px] font-semibold text-brand-text">Coming soon</span>}
      </div>
      {children}
    </section>
  );
}

const INTEGRATIONS = ["Zoom", "Google Meet", "Microsoft Teams", "Google Calendar", "Slack", "Salesforce", "HubSpot", "Notion"];

export function SettingsView() {
  const { data: me } = useMe();
  const { theme, setTheme } = useTheme();
  const soon = () => toast.info("Coming soon", { description: "This setting is a placeholder in the demo." });

  return (
    <div className="mx-auto max-w-3xl space-y-5 px-4 py-6 sm:px-6">
      <div>
        <h1 className="text-xl font-semibold tracking-tight">Settings</h1>
        <p className="mt-0.5 text-sm text-muted">Manage your profile, preferences and integrations</p>
      </div>

      <Card title="Profile" description="Authentication is mocked; you're signed in as the demo user.">
        <div className="flex items-center gap-4">
          <Avatar name={me?.user.name ?? "User"} color={me?.user.avatar_color} size="lg" />
          <div className="grid flex-1 gap-3 sm:grid-cols-2">
            <Field label="Name" htmlFor="settings-name">
              <Input id="settings-name" value={me?.user.name ?? ""} readOnly />
            </Field>
            <Field label="Email" htmlFor="settings-email">
              <Input id="settings-email" value={me?.user.email ?? ""} readOnly />
            </Field>
          </div>
        </div>
      </Card>

      <Card title="Appearance" description="Choose how the workspace looks.">
        <Field label="Theme" htmlFor="settings-theme">
          <Select id="settings-theme" value={theme ?? "light"} onChange={(e) => setTheme(e.target.value)} className="max-w-48">
            <option value="light">Light</option>
            <option value="dark">Dark</option>
          </Select>
        </Field>
      </Card>

      <Card title="AI notes" description="How summaries, action items and answers are generated.">
        <p className="text-sm">
          {me?.llm_enabled ? (
            <>
              Using <strong>{me.llm_model}</strong> to generate notes and answer questions.
            </>
          ) : (
            <>No LLM key is configured, so notes are generated by the built-in extractive summarizer. Set <code className="rounded bg-surface-hover px-1">ANTHROPIC_API_KEY</code> on the backend to enable Claude.</>
          )}
        </p>
      </Card>

      <Card title="Integrations" description="Connect your calendar, conferencing and CRM tools." soon>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          {INTEGRATIONS.map((name) => (
            <button key={name} onClick={soon} className="rounded-lg border border-border px-3 py-2.5 text-left text-sm font-medium hover:bg-surface-hover">
              {name}
              <span className="block text-xs font-normal text-subtle">Connect</span>
            </button>
          ))}
        </div>
      </Card>

      <Card title="Notetaker" description="Let the Fireflies bot join and record your calls automatically." soon>
        <Button onClick={soon}>Configure auto-join</Button>
      </Card>

      <Card title="Team & sharing" description="Invite teammates and control who can see your meetings." soon>
        <Button onClick={soon}>Invite teammates</Button>
      </Card>
    </div>
  );
}
