import { screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it } from "vitest";

import { NotesPanel, generatorLabel } from "@/components/meeting/NotesPanel";
import { SpeakersPanel, speakerStats } from "@/components/meeting/SpeakersPanel";
import { meetingDetail } from "@/test/fixtures";
import { renderWithPlayer } from "@/test/utils";

describe("NotesPanel", () => {
  it("renders overview, keywords, notes, outline and action items", () => {
    renderWithPlayer(<NotesPanel meeting={meetingDetail()} />);
    expect(screen.getByText("The team reviewed the pricing page.")).toBeInTheDocument();
    expect(screen.getByText("SSO")).toBeInTheDocument();
    expect(screen.getByText("💡 Enterprise tier needs SSO")).toBeInTheDocument();
    expect(screen.getByText("Launch email")).toBeInTheDocument();
    expect(screen.getByText("Draft the launch email")).toBeInTheDocument();
  });

  it("seeks to a chapter when it is clicked", async () => {
    renderWithPlayer(<NotesPanel meeting={meetingDetail()} />);
    await userEvent.click(screen.getByText("Launch email"));
    expect(screen.getByTestId("harness-time")).toHaveTextContent("16");
    expect(screen.getByText("Launch email").closest("button")).toHaveAttribute("aria-current", "step");
  });

  it("shows an empty state without notes", () => {
    renderWithPlayer(<NotesPanel meeting={meetingDetail({ summary: null, chapters: [] })} />);
    expect(screen.getByText("No notes yet")).toBeInTheDocument();
  });

  it("labels how notes were generated", () => {
    expect(generatorLabel("llm:claude-opus-5")).toBe("Generated by claude-opus-5");
    expect(generatorLabel("heuristic")).toBe("Generated from transcript");
  });
});

describe("SpeakersPanel", () => {
  it("computes talk-time share", () => {
    const stats = speakerStats(meetingDetail());
    expect(stats.map((s) => [s.name, s.share])).toEqual([
      ["Dana Lee", 73],
      ["Sam Ortiz", 27],
    ]);
    renderWithPlayer(<SpeakersPanel meeting={meetingDetail()} />);
    expect(screen.getByText(/73%/)).toBeInTheDocument();
  });
});
