"use client";

import { ListTree, Sparkles, Tags } from "lucide-react";

import { EmptyState } from "@/components/ui/States";
import { formatClock } from "@/lib/format";
import { usePlayer } from "@/lib/player";
import type { MeetingDetail } from "@/lib/types";

import { Timestamp } from "./Timestamp";

function Section({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <section className="mb-6">
      <h3 className="mb-2 flex items-center gap-2 text-[13px] font-semibold uppercase tracking-wide text-muted">
        {icon}
        {title}
      </h3>
      {children}
    </section>
  );
}

export function generatorLabel(generatedBy: string): string {
  if (generatedBy.startsWith("llm:")) return `Generated by ${generatedBy.slice(4)}`;
  if (generatedBy === "seed") return "AI notes";
  return "Generated from transcript";
}

export function NotesPanel({ meeting }: { meeting: MeetingDetail }) {
  const player = usePlayer();
  const { summary, chapters } = meeting;

  if (!summary && !chapters.length) {
    return <EmptyState title="No notes yet" description="Notes are generated automatically when a meeting has a transcript." />;
  }

  const currentChapter = chapters.findLast((c) => c.start_seconds <= player.currentTime + 0.5)?.id;

  return (
    <div>
      {summary && (
        <>
          {summary.keywords.length > 0 && (
            <Section icon={<Tags className="size-3.5" />} title="Keywords">
              <div className="flex flex-wrap gap-1.5">
                {summary.keywords.map((k) => (
                  <span key={k} className="rounded-control bg-surface-hover px-2 py-0.5 text-xs font-medium text-text">
                    {k}
                  </span>
                ))}
              </div>
            </Section>
          )}
          <Section icon={<Sparkles className="size-3.5" />} title="Overview">
            <p className="text-[14px] leading-relaxed">{summary.overview}</p>
            <p className="mt-1.5 text-[11px] text-subtle">{generatorLabel(summary.generated_by)}</p>
          </Section>
          {summary.bullet_points.length > 0 && (
            <Section icon={<span className="text-sm">📝</span>} title="Notes">
              <ul className="space-y-2">
                {summary.bullet_points.map((b, i) => (
                  <li key={i} className="text-[14px] leading-relaxed">
                    {b}
                  </li>
                ))}
              </ul>
            </Section>
          )}
        </>
      )}
      {chapters.length > 0 && (
        <Section icon={<ListTree className="size-3.5" />} title="Outline">
          <ol className="space-y-1">
            {chapters.map((c) => (
              <li key={c.id}>
                <button
                  onClick={() => player.seek(c.start_seconds, { play: true })}
                  aria-current={c.id === currentChapter ? "step" : undefined}
                  className="w-full rounded-control px-2.5 py-2 text-left transition hover:bg-surface-hover aria-[current=step]:bg-brand-soft"
                >
                  <span className="flex items-baseline gap-2">
                    <span className="font-mono text-xs tabular-nums text-brand-text">{formatClock(c.start_seconds)}</span>
                    <span className="text-sm font-semibold">{c.title}</span>
                  </span>
                  {c.summary && <span className="mt-0.5 block pl-12 text-[13px] leading-snug text-muted">{c.summary}</span>}
                </button>
              </li>
            ))}
          </ol>
        </Section>
      )}
      {summary && meeting.action_items.length > 0 && (
        <Section icon={<span className="text-sm">✅</span>} title="Action items">
          <ul className="space-y-1.5">
            {meeting.action_items.map((a) => (
              <li key={a.id} className="flex items-start gap-2 text-[14px]">
                <span className={a.is_completed ? "text-muted line-through" : ""}>
                  {a.assignee && <strong className="font-semibold">{a.assignee.name}: </strong>}
                  {a.text}
                </span>
                {a.timestamp_seconds !== null && <Timestamp seconds={a.timestamp_seconds} className="shrink-0" />}
              </li>
            ))}
          </ul>
        </Section>
      )}
    </div>
  );
}
